repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev:  v1.76.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
      - id: terraform_tflint
        args:
          - --args=--disable-rule=terraform_required_version
          - --args=--disable-rule=terraform_required_providers
      - id: terraform_tfsec
      - id: terrascan

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
